### ISSUE TITLE
Error DLL mozglue

### ISSUE THREAD

**Issue by xswapper15** [galodoido794/AUTOBOT_FIFAX#17]
link da imagem --> https://uploaddeimagens.com.br/images/001/847/538/original/ErroFif.png?1548091614

Windows 10 64-BIT 
Firefox instalado e definido como navegador padrão.

**Comment by galodoido794** [comment]
Você chegou a instalar os pré-requisitos?

[Net471](
https://www.microsoft.com/net/download/dotnet-framework-runtime/net471)

[vc_redist.x86.exe](
https://aka.ms/vs/15/release/vc_redist.x86.exe
)

Se ja instalou tente isso:
[https://support.mozilla.org/pt-BR/questions/1199558](https://support.mozilla.org/pt-BR/questions/1199558)

**Comment by galodoido794** [comment]
[en-US]
* Removed dependency on Firefox
* Performance improvement of 10 to 30%
* In the search of the players now is not obligatory the quality, however can buy Gold instead of a Special.
* Package almost 20 megs smaller.

[pt-br]
* Retirado a dependência do Firefox
* Melhoria de desempenho de 10 a 30%
* Na busca dos jogadores agora não é obrigatório a qualidade, entretanto pode comprar Gold ao invés de um Special.
* Pacote quase 20 megas menor.


DOWNLOAD: https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.11/AUTOBOT_FIFAXv_1_11.7z
