### ISSUE TITLE
Issue with mozglue

### ISSUE THREAD

**Issue by gl4doss** [galodoido794/AUTOBOT_FIFAX#19]
Hello, I'm having problem with mozglue dll, so I downloaded it and now it's xul.dll error. Win 10 with firefox reinstalled. Also did the insctructions on the link on issue #17 ﻿

**Comment by galodoido794** [comment]
[en-US]
* Removed dependency on Firefox
* Performance improvement of 10 to 30%
* In the search of the players now is not obligatory the quality, however can buy Gold instead of a Special.
* Package almost 20 megs smaller.

[pt-br]
* Retirado a dependência do Firefox
* Melhoria de desempenho de 10 a 30%
* Na busca dos jogadores agora não é obrigatório a qualidade, entretanto pode comprar Gold ao invés de um Special.
* Pacote quase 20 megas menor.


DOWNLOAD: https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.11/AUTOBOT_FIFAXv_1_11.7z
