### ISSUE TITLE
Why is you bot mining on coinhive?

### ISSUE THREAD

**Issue by VatsaPatel** [galodoido794/AUTOBOT_FIFAX#20]
Why is you bot mining on coinhive? There are multiple requests to coinhive.com from your bot. Lets be transparent about this if you are mining on our systems.

**Comment by VatsaPatel** [comment]
Seems to go away with system wide adblock.

**Comment by galodoido794** [comment]
[en-US]
* Removed dependency on Firefox
* Performance improvement of 10 to 30%
* In the search of the players now is not obligatory the quality, however can buy Gold instead of a Special.
* Package almost 20 megs smaller.

[pt-br]
* Retirado a dependência do Firefox
* Melhoria de desempenho de 10 a 30%
* Na busca dos jogadores agora não é obrigatório a qualidade, entretanto pode comprar Gold ao invés de um Special.
* Pacote quase 20 megas menor.


DOWNLOAD: https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.11/AUTOBOT_FIFAXv_1_11.7z
