### ISSUE TITLE
 "Are you logged into fifa? check.."

### ISSUE THREAD

**Issue by poruzuni** [galodoido794/AUTOBOT_FIFAX#22]
Primeiramente obrigado pelo bot =D tava funcionando perfeitamente, ai começou  a dar "Are you logged into fifa? check.." como resolve ?﻿

**Comment by galodoido794** [comment]
Voltou a funcionar ou continua com erro?

**Comment by VatsaPatel** [comment]
Bot is working atm. You must sometimes complete captcha if too many requests.

**Comment by VatsaPatel** [comment]
@galodoido794 , can you please expose 6 inputs to create custom filters or just even remove requirement to select quality? Thanks in advance.

**Comment by galodoido794** [comment]
Since I have little support at Patreon I can THINK of working on this feature tomorrow

**Comment by VatsaPatel** [comment]
@galodoido794 , thanks for even considering it.

**Comment by galodoido794** [comment]
=D
[Patreon](https://www.patreon.com/galodoido)

**Comment by ubaniakande** [comment]
Yes hello, my friend is having trouble with the autobuyer, he cant seem to get it to work it also was says "false response message null" can you help?

**Comment by VatsaPatel** [comment]
> Since I have little support at Patreon I can THINK of working on this feature tomorrow
@galodoido794 
Sorry to pester, but any updates?

**Comment by VatsaPatel** [comment]
@galodoido794 , any updates?

**Comment by galodoido794** [comment]
> 
> 
> Yes hello, my friend is having trouble with the autobuyer, he cant seem to get it to work it also was says "false response message null" can you help?

Try to do the following:
1) Tab Problem
2) Alter Server (change and send search)
Maybe this will solve

New Version 1.11
DOWNLOAD: [AUTOBOT_1.11](https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.11/AUTOBOT_FIFAXv_1_11.7z)

[en-US]
* Removed dependency on Firefox
* Performance improvement of 10 to 30%
* In the search of the players now is not obligatory the quality, however can buy Gold instead of a Special.
* Package almost 20 megs smaller.

[pt-br]
* Retirado a dependência do Firefox
* Melhoria de desempenho de 10 a 30%
* Na busca dos jogadores agora não é obrigatório a qualidade, entretanto pode comprar Gold ao invés de um Special.
* Pacote quase 20 megas menor.

**Comment by romariofc** [comment]
Baixei esse novo arquivo e ainda continua o problema, pode me ajudar por favor?
